// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnzcfoinedwuyrthpljh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuemNmb2luZWR3dXlydGhwbGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzA2MzMsImV4cCI6MjA2NzE0NjYzM30.PDBMpKTUs4FCPGIgJx-kcw4FK-N0JCYZXbXURu9gkEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});